jobs:
- job: BuildSDK
  pool:
    vmImage: vs2017-win2016

  steps:

- task: MSBuild@1
  inputs:
    solution: 'Html5Sdk.sln'
    msbuildVersion: '14.0' # Optional. Options: latest, 15.0, 14.0, 12.0, 4.0
    #msbuildArchitecture: 'x86' # Optional. Options: x86, x64
    clean: true # Optional
