jobs:
- job: BuildSDK
  pool:
    vmImage: vs2015-win2012r2

  steps:

  - task: MSBuild@1
    inputs:
      solution: 'Html5Sdk.sln'
      msbuildVersion: '14.0'
      msbuildArchitecture: 'x64'
      clean: true

  - task: NodeTool@0

  - script: npm install
    workingDirectory: 'webclient'
    displayName: Install NPM dependencies

  - script: npm install -g grunt-cli
    workingDirectory: 'webclient'
    displayName: Installing grunt

  - task: Grunt@0
    inputs:
      gruntFile: 'webclient\Gruntfile.js'
      targets: sdk
      workingDirectory: 'webclient'

  - task: CopyFiles@2
    inputs:
      sourceFolder: 'webclient\sdk'
      contents: 'wwtsdk.js'
      targetFolder: $(Build.ArtifactStagingDirectory)
      cleanTargetFolder: true

  - task: PublishPipelineArtifact@0
    inputs:
      artifactName: wwtsdk.js
      targetPath: $(Build.ArtifactStagingDirectory)
